#! /bin/bash
echo "== Demo Menu =="
if [ $# -ne 0 ]
then
    case $1 in

    1 | "doors" | "door_demo" | "prox" | "proximity" | "proximity doors")
        echo "Running proximity door demo"
        ./build && docker run --cap-add=SYS_ADMIN -it vxbot npm run demo_picker $1
        ;;

    2 | "rosie" | "Rosie" )
        echo "Rosie demo currently under development"
        ./build && docker run --cap-add=SYS_ADMIN -it vxbot npm run demo_picker $1
        ;;

    3 | "image" | "sequence" | "image sequence" )
        echo "Image sequence demo currently under development"
        ./build && docker run --cap-add=SYS_ADMIN -it vxbot npm run demo_picker $1
        ;;
    
    4 | "slides" | "slide deck" )
        echo "Slide deck demo currently under development"
        ./build && docker run --cap-add=SYS_ADMIN -it vxbot npm run demo_picker $1
        ;;
    5 | "fire" | "fire exit" )
        echo "Fire Exit demo currently under development"
        ./build && docker run --cap-add=SYS_ADMIN -it vxbot npm run demo_picker $1
        ;;

    *)
        echo "usage: $0 [demo-name OR demo-number]"
        echo ""
        echo "Please select a demo to run"
        echo "1. Proximity doors"
        echo "2. Rosie"
        echo "3. Image sequence"
        echo "4. Slide Deck (WIP)"
        echo "5. Fire Exit"
        ;;
    esac
else
    echo "No arguments detected"
    echo "usage: $0 [demo-name OR demo-number]"
    echo ""
    echo "Please select a demo to run"
    echo "1. Proximity doors"
    echo "2. Rosie"
    echo "3. Image sequence"
    echo "4. Slide Deck (WIP)"
    echo "5. Fire Exit"
fi